version: "3.9"

services:
  db:
    image: postgres:16
    container_name: qms_db
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d railway"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: qms_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/railway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      JWT_SECRET: change-me-very-long-random-string
      SECURITY_JWT_EXPIRATION_MS: 86400000
      CORS_ALLOWED_ORIGINS: http://localhost:8080,https://bank-queue-service-production.up.railway.app
    ports:
      - "8080:8080"

volumes:
  dbdata:
